exports.homepage=(req,res)=>{
        res.render("home.ejs");
}
exports.adminLogin=(req,res)=>{
        res.render("loginpage.ejs");
}
exports.admindash=(req,res)=>{
        res.render("admindashboard.ejs");
}